# Generated by Django 3.2.6 on 2021-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todolist_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
