# Generated by Django 3.2.6 on 2021-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todolist_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
