# Generated by Django 3.2.6 on 2021-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolist_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='subject',
            field=models.CharField(blank=True, choices=[('Web', 'web'), ('Big data', 'big_data'), ('NLP', 'nlp'), ('Deep learning', 'deep_learning'), ('Machine learning', 'machine_learning')], max_length=100, null=True),
        ),
    ]
