# Generated by Django 3.2.6 on 2021-08-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todolist_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='subject',
            field=models.CharField(blank=True, choices=[('Web', 'Web'), ('Big data', 'Big data'), ('NLP', 'NLP'), ('Deep learning', 'Deep learning'), ('Machine learning', 'Machine learning')], max_length=100, null=True),
        ),
    ]
