# Generated by Django 3.2.6 on 2021-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_project_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
